version: "3.7"

services:
  00.mariadb:
    image: mariadb:10.2.15
    container_name: 00.mariadb
    hostname: 00.mariadb.local
    restart: unless-stopped
    env_file:
      - envs/global.env-template
      - envs/00.env-template
    volumes:
      - ./data/01/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep-new-cluster
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.10
    networks:
      databases:
        ipv4_address: 10.5.0.10

  01.mariadb:
    image: mariadb:10.2.15
    container_name: 01.mariadb
    hostname: 01.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/01/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.11
    networks:
      databases:
        ipv4_address: 10.5.0.11

  02.mariadb:
    image: mariadb:10.2.15
    container_name: 02.mariadb
    hostname: 02.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/02/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.12
    networks:
      databases:
        ipv4_address: 10.5.0.12

  03.mariadb:
    image: mariadb:10.2.15
    container_name: 03.mariadb
    hostname: 03.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/03/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.13
    networks:
      databases:
        ipv4_address: 10.5.0.13

  04.mariadb:
    image: mariadb:10.2.15
    container_name: 04.mariadb
    hostname: 04.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/04/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.14
    networks:
      databases:
        ipv4_address: 10.5.0.14

  05.mariadb:
    image: mariadb:10.2.15
    container_name: 05.mariadb
    hostname: 05.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/05/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.15
    networks:
      databases:
        ipv4_address: 10.5.0.15

  06.mariadb:
    image: mariadb:10.2.15
    container_name: 06.mariadb
    hostname: 06.mariadb.local
    restart: always
    env_file:
      - envs/global.env-template
    volumes:
      - ./data/06/:/var/lib/mysql
      - ./data/conf.d/:/etc/mysql/mariadb.conf.d
    command:
      - --wsrep_cluster_name=galera
      - --wsrep_cluster_address=gcomm://10.5.0.10,10.5.0.11,10.5.0.12,10.5.0.13,10.5.0.14,10.5.0.15,10.5.0.16
      - --wsrep_sst_auth=root:secret
      - --wsrep_node_address=10.5.0.16
    networks:
      databases:
        ipv4_address: 10.5.0.16

networks:
  databases:
    name: databases
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.5.0.0/24